"""Obsidian Bases views and page templates (Round 101, B13).

    python -m knowledge.views [--force] [--dry-run]

Writes wiki/_views/<name>.base (Obsidian 1.9+ Bases: YAML with `filters` and `views`)
for the compiled types, and wiki/_templates/<kind>.md scaffolds whose frontmatter
already satisfies OKF v0.2 (`type`, `generated.by: human:operator`, ...), so a page a
human creates from a template passes lint L1 the moment it is saved. Folders whose
name starts with `_` are tooling, not pages: lint and the index skip them.

Bases filters use `file.inFolder(...)`, which matches the folder-per-type layout of
WIKI_SCHEMA.md s.4 and needs no property that a nested `dev:` mapping would hide.
Settings the operator should make in Obsidian (never written by this package):
Templates -> template folder `wiki/_templates`; Daily notes -> folder `journal`.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import DEV_ROOT, EXIT_HALT, EXIT_OK, VAULT, halted
from .pages import assert_owned

VIEWS_DIR = Path("wiki") / "_views"
TEMPLATES_DIR = Path("wiki") / "_templates"


@dataclass(frozen=True)
class View:
    name: str
    title: str
    folder: str
    columns: tuple[str, ...]
    description: str


VIEWS: tuple[View, ...] = (
    View("rulings", "Rulings", "wiki/rulings", ("file.name", "title", "status", "stale_after", "tags"),
         "Every Ruling page: the R-series and every extracted Directive / Ratification / Ruling N-N."),
    View("experiments", "Experiments", "wiki/experiments", ("file.name", "title", "status", "tags"),
         "Pre-registrations, archived controls and verdicts."),
    View("markets", "Markets", "wiki/markets", ("file.name", "title", "status", "resource"),
         "Polymarket markets the wiki is bound to; deprecated when the token leaves the drops."),
    View("profiles", "Reaction profiles", "wiki/profiles", ("file.name", "title", "status"),
         "Post-print depth survival, one page per event x market."),
    View("crm", "CRM", "crm", ("file.name", "type", "title", "status"),
         "Titans, whales, sharps and sportsbooks; judgement is human, evidence appended."),
    View("journal", "Journal", "journal", ("file.name", "title", "status"),
         "One page per trading day: executions, calibration ledger, debrief."),
    View("events", "Events", "wiki/events", ("file.name", "title", "status", "stale_after"),
         "Scheduled prints with their windows, tax deadlines, recorded events."),
)


def base_yaml(v: View) -> str:
    doc = {
        "filters": {"and": [f'file.inFolder("{v.folder}")', 'file.ext == "md"']},
        "properties": {c: {"displayName": c.split(".")[-1].replace("_", " ")} for c in v.columns if not c.startswith("file.")},
        "views": [{"type": "table", "name": v.title, "order": list(v.columns)}],
    }
    header = f"# {v.title}: {v.description}\n# Generated by knowledge.views (Round 101); regenerate with `python -m knowledge.views --force`.\n"
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, default_flow_style=False)


TEMPLATES: dict[str, str] = {
    "postmortem": """---
type: Post-mortem
title: "Post-mortem: {{title}}"
description: One sentence on what happened and what it cost.
tags: [postmortem, human]
generated:
  by: human:operator
  at: "{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}Z"
status: draft
# stale_after: add "YYYY-MM-DDT00:00:00Z" 90 days out if this page should be re-read (Concept policy); lint L7 nudges Concepts only
sources:
  - id: raw
    resource: obsidian_vault/raw/postmortems/REPLACE-ME.md
    title: the raw write-up
    author: human:operator
dev:
  desk: 0
  relations: []
---

# Post-mortem: {{title}}

## What happened

## What it cost

## What the rules said, and whether they were followed

## What changes (link the Ruling that follows, or write `none`)

## Related

- [[Desk_03_Cross_Market_Desk|Desk]]
""",
    "memo": """---
type: Memo
title: "Memo: {{title}}"
description: One sentence.
tags: [memo, human]
generated:
  by: human:operator
  at: "{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}Z"
status: draft
sources:
  - id: raw
    resource: obsidian_vault/raw/memos/REPLACE-ME.md
    title: the transcript or note
    author: human:operator
---

# Memo: {{title}}

## Note

## Actions

## Related

""",
    "contact": """---
type: Contact
title: "{{title}}"
description: Who this is and why the desk talks to them.
tags: [crm, contact, human]
generated:
  by: human:operator
  at: "{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}Z"
status: draft
dev:
  desk: 0
  role: REPLACE-ME (accountant | prop firm | broker | counterparty)
---

# {{title}}

## Identity

## Judgement

## Evidence (dated rows; append, never rewrite)

| at | note |
|---|---|

## Related

- [[crm_register|CRM register]]
""",
    "thesis": """---
type: Concept
title: "{{title}}"
description: The claim in one sentence.
tags: [concept, thesis, human]
generated:
  by: human:operator
  at: "{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}Z"
status: draft
# stale_after: "YYYY-MM-DDT00:00:00Z" 90 days from today (Concept policy). Until you set it, lint L7 warns on this page - that is the nudge.
sources:
  - id: source
    resource: REPLACE-ME (a path in the repo, git:<sha>, or https://...)
    title: where the claim comes from
dev:
  desk: 0
  parameters: []
  relations: []
---

# {{title}}

## Claim

## Evidence

## What would change my mind

## Related

""",
}


def write_views(vault: Path, *, force: bool = False, dry_run: bool = False) -> tuple[list[str], list[str]]:
    written: list[str] = []
    skipped: list[str] = []
    targets: list[tuple[Path, str]] = [(vault / VIEWS_DIR / f"{v.name}.base", base_yaml(v)) for v in VIEWS]
    targets += [(vault / TEMPLATES_DIR / f"{k}.md", body) for k, body in TEMPLATES.items()]
    for path, text in targets:
        assert_owned(path, vault)
        rel = path.relative_to(vault).as_posix()
        if path.exists() and not force:
            skipped.append(rel)
            continue
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
        written.append(rel)
    return written, skipped


def main(argv: list[str] | None = None, out=None) -> int:
    out = out or sys.stdout
    ap = argparse.ArgumentParser(prog="knowledge.views", description=__doc__.split("\n\n")[0])
    ap.add_argument("--vault", type=Path, default=VAULT)
    ap.add_argument("--dev-root", type=Path, default=DEV_ROOT)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)
    if halted(args.dev_root):
        print(f"[HALT] {args.dev_root / 'HALT.flag'} present - views refuses (exit {EXIT_HALT})", file=out)
        return EXIT_HALT
    if not args.vault.is_dir():
        print(f"[REFUSE] vault not found: {args.vault} (exit {EXIT_HALT})", file=out)
        return EXIT_HALT
    written, skipped = write_views(args.vault, force=args.force, dry_run=args.dry_run)
    for r in written:
        print(("[DRY]   " if args.dry_run else "[WRITE] ") + r, file=out)
    for r in skipped:
        print("[KEEP]  " + r, file=out)
    print(f"views: {len(written)} written, {len(skipped)} kept ({len(VIEWS)} .base views, {len(TEMPLATES)} templates)", file=out)
    return EXIT_OK


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
